### ISSUE TITLE
running in browser; can't get protobufjs/minimal to resolve

### ISSUE THREAD

**Issue by NigelThorne** [nicdex/node-eventstore-client#100]
Create a simple react app
yarn add node-eventstore-client
import it in app.js
![image](https://user-images.githubusercontent.com/5942/85809738-3b8b7d80-b79c-11ea-9b48-2b0af1969204.png)

**Comment by nicdex** [comment]
This library doesn't run in browser, that's why the project is prefixed with node- :/

**Comment by NigelThorne** [comment]
lol. Thanks
