### ISSUE TITLE
Handle Large events 

### ISSUE THREAD

**Issue by MarshallRJ** [nicdex/node-eventstore-client#29]
I am having an issue with handling events the have large size (> 3mb)

There a few such events on some of the streams in the eventstore I am using. According to this issue [(issue: 899)](https://github.com/EventStore/EventStore/issues/899) on the EventStore repo the largest size allowed is 16mb although it is recommended to have have events smaller than 2mb.

When attempting to read the the event there is connection retry limit exceed error thrown shown below:

Error: Retry limit reached. Operation: Operation ReadStreamEventsForwardOperation (5fc60d08-a0d9-47a3-9fb2-d229a5e5de84): Stream: Meter-88912334, FromEventNumber: 11510, MaxCount: 10, ResolveLinkTos: true, RequireMaster: true, retry count: 10, created: 08:01:01.488, last updated: 08:01:46.648, RetryCount: 10

I wrote a test to replicate the issue in this pull request [Large Events Test](https://github.com/nicdex/eventstore-node/pull/28). The append test fails with a different exception shown below: 

Error: Bad request: Could not unwrap network package for command WriteEvents.

    at AppendToStreamOperation.OperationBase._inspectBadRequest (/mnt/c/projects/rjmarshall/eventstore-node/src/clientOperations/operationBase.js:104:13)
    at AppendToStreamOperation.OperationBase.inspectPackage (/mnt/c/projects/rjmarshall/eventstore-node/src/clientOperations/operationBase.js:74:21)
    at EventStoreConnectionLogicHandler._handleTcpPackage (/mnt/c/projects/rjmarshall/eventstore-node/src/core/eventStoreConnectionLogicHandler.js:501:38)
    at /mnt/c/projects/rjmarshall/eventstore-node/src/core/eventStoreConnectionLogicHandler.js:92:10
    at Immediate._handlers.(anonymous function) (/mnt/c/projects/rjmarshall/eventstore-node/src/core/simpleQueuedHandler.js:19:7)
    at runCallback (timers.js:653:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)

**Comment by nicdex** [comment]
That error means that the tcp package is over the 16mb limit.

I looked over the tests you provided and it generates a data of 18mb for the event.
Buffer.alloc(3 * 1024 *1024, 1).toString() returns a "binary" string and JSON.stringify will encode that string using special utf8 char (all ascii 1 will be replaced with \u0001) multiplying size by 6.

I'm not sure what kind of data you want to add in your event, but if you store them as "binary" string I would suggest you use base64 encoding.

I don't have any control over what JSON.stringify does. If you want to provide a different format (other than json, or use different json encoder) you can use the esClient.createEventData instead which takes Buffers as parameters.

**Comment by nicdex** [comment]
Tests are passing if using non binary string. See https://github.com/nicdex/eventstore-node/commit/85814ed03f9eec767be02ae4d2bcf609b38e840c

**Comment by MarshallRJ** [comment]
Thanks for the update and the explanation. I will investigate the encoding on our events.

**Comment by nicdex** [comment]
Is this issue resolved, can I close it?

**Comment by MarshallRJ** [comment]
Yes. Thanks. I will close.
