### ISSUE TITLE
docs are down

### ISSUE THREAD

**Issue by reharik** [nicdex/node-eventstore-client#37]
Hi, first thank you for this work, I am using it and appreciate it.
second, the link to your docs is down.
third, did you change the name?  npm has it as node-eventstore but yoru repo seems to be node-eventstore-client and the readme says to install it via node-eventstore-client.
maybe it's always been this way,  I can't remember.
thanks,
R

**Comment by nicdex** [comment]
Sorry I fixed the docs, I forgot to rename the path.

**Comment by nicdex** [comment]
Project was renamed from "eventstore-node" to "node-eventstore-client" after version 0.1.2
Subscribe to #22 if you want to be kept informed of CHANGELOG.
Thanks
