### ISSUE TITLE
Hard deleted stream events are emitted with subscribeToAllFrom

### ISSUE THREAD

**Issue by kmalakoff** [nicdex/node-eventstore-client#39]
If you hard delete a stream using something like:

```
await this.connection.deleteStream(streamName, sequence, true, credentials)
```

When you use `subscribeToAllFrom`, the streams are deleted, but the events are still returned by the iteration callback. 

I have checked the metadata for the stream in the callback and it shows up as deleted and you cannot view the stream in the admin UI so there is probably a bug.

**Comment by nicdex** [comment]
The nodejs client is replicating the behavior of the .Net client. I think this is because $all is a special stream on the server. You need to bring up that issue with EventStore directly at https://github.com/EventStore/EventStore/issues. That being said I'm pretty sure it's the desired behavior.

**Comment by kmalakoff** [comment]
Ok. Will do!
