### ISSUE TITLE
Best method to clear user streams for unit tests

### ISSUE THREAD

**Issue by kmalakoff** [nicdex/node-eventstore-client#40]
I am currently processing $all events to find the last version so that I can delete streams between each unit test, but I was wondering if there is a more efficient method to do this.

**Comment by nicdex** [comment]
Deleting is not a good scenario when working with EventStore. The only reason "delete" exists is to allow scavenging of disk space from unused events. Scavenging will only affect completed chunk of the log, not the latest data.

I would suggest using a setup to create a new unique user each time (i.e. user-${uuidOrIncrementalValueHere}) and no teardown. Run the eventstore in memory (with --memdb) so data doesn't persist.

**Comment by kmalakoff** [comment]
It is pretty common to clear storage between tests. Having to manually work around a common scenario is a worst case scenario for me.

Sorry, but I'm not interested in workarounds. I am looking for suggestions on how to clear the event store cleanly for testing purposes.

**Comment by nicdex** [comment]
It's a feature request to raise with the EventStore team. This is out of my control, the client only replicates the behavior of the .Net Client and this is a server side issue.

**Comment by kmalakoff** [comment]
Done: https://github.com/EventStore/EventStore/issues/1328

Thank you!
