### ISSUE TITLE
Catch-up subscription receives first event when lastCheckpoint is 0

### ISSUE THREAD

**Issue by aikoven** [nicdex/node-eventstore-client#41]
When I set `lastCheckpoint` to a positive `N`, the callback receives events with numbers `N+1`, `N+2`, ...

But if `lastCheckpoint` is set to `0`, it receives `0`, `1`, `2`, ... 

Is this intended? I'd expect this to happen only if `lastCheckpoint` is `null`.

**Comment by nicdex** [comment]
You are right setting lastCheckpoint to 0 should only return events 1, 2, ...

Fixing this now. Should have a new package released later today.
