### ISSUE TITLE
Typings for Persistent subscription are missing.

### ISSUE THREAD

**Issue by sledorze** [nicdex/node-eventstore-client#42]
Would you mind adding it to the index.d.ts file?
Thanks for that lib!

**Comment by nicdex** [comment]
Fixed in release 0.1.5

Let me know if something else is missing. Maintaining the typescript definition is complicated for me since I don't use typescript. Any contributions (PR) on that front would be great.

**Comment by sledorze** [comment]
@nicdex Oh.. ok I understand that, then thanks for the extra effort!

not wanting to bug you on that; have you ever considered moving the project to Typescript ?
It can help a lot without getting too much in the way even introduced incrementally
> https://github.com/Microsoft/TypeScript/wiki/Type-Checking-JavaScript-Files

Thanks again :)
