### ISSUE TITLE
Projections

### ISSUE THREAD

**Issue by sledorze** [nicdex/node-eventstore-client#43]
There no visible API for projections in this Client.
I'm wondering if that could be added or if it should be out of scope for that project (and why).

**Comment by nicdex** [comment]
As far as I know that's not part of the TCP protocol. I'll doublecheck this. Projections handling should be a side module.

**Comment by nicdex** [comment]
It seems there is a ProjectionManager provided with the C# client. It's a completely separate "client" as it operates over HTTP instead of TCP. I will add this to the list of missing features and will look into implementing it in the next month.

**Comment by sledorze** [comment]
awesome @nicdex ! :)

**Comment by nicdex** [comment]
Implemented in 0.1.9
