### ISSUE TITLE
the connectionName passed to createConnection method is not shown in the EventStore UI

### ISSUE THREAD

**Issue by riccardone** [nicdex/node-eventstore-client#48]
I'm using the EventStore v 4.0.1

Thanks

**Comment by nicdex** [comment]
This is a new feature from v4 protocol which is not implemented yet.
#31

**Comment by riccardone** [comment]
can I help just for this specific one or do you prefer implement all the enhancement with a separate story?

**Comment by nicdex** [comment]
I don't think it can be implemented separately. I'll try to implement v4 protocol in the next two weeks.

**Comment by nicdex** [comment]
See https://github.com/nicdex/node-eventstore-client/issues/22#issuecomment-342956291

**Comment by riccardone** [comment]
@nicdex I'm using the latest 0.1.11 version with EventStore 4.0.3.3 but I still can't see the connection name shown in the EventStore UI
This is my code to create the connection:
`esClient.createConnection({'admin':'changeit'}, 'tcp://eventstore:1113', 'test')`
and the EventStore UI shown "N/A" under the 'Client Connection Name' Connections column

**Comment by riccardone** [comment]
As said, this issue is still there. I wonder if you want me to open another issue?

**Comment by nicdex** [comment]
Darn npm versioning. I pushed a fix for the 0.1.x branch, so 1.1.11 indicate as latest, but highest version is 0.2.1.
Branch 0.2.x are the one compatible with the EventStore v4 protocol. Use npm install eventstore@^0.2 to install it.
