### ISSUE TITLE
Error: Package size is out of bounds

### ISSUE THREAD

**Issue by aikoven** [nicdex/node-eventstore-client#51]
I am getting the following error:
```
[ERROR] Error: Package size is out of bounds: 91150338(max: 67108864
```
This happens while establishing a connection.

Is there a way I can configure maximal package size?

**Comment by nicdex** [comment]
There is no way to configure that value, it is set to 64MB.
This should not happen and it's probably indicative of another problem.

Can you give me the version of the EventStore you are using.
Also the output of these commands run in your project folder:
* node -e "console.log(process.version, process.platform, process.arch)"
* npm ls node-eventstore-client long protobufjs

Thanks

**Comment by aikoven** [comment]
I'm sorry, I've missed your reply. 

This was indeed due to a bug in my code which resulted in huge event payloads. Still, these events were written successfully but caused errors when read later (I guess).

I'm using EventStore 4.0.3.

```
# node -e "console.log(process.version, process.platform, process.arch)"
v7.10.1 linux x64
```

```
# npm ls node-eventstore-client long protobufjs
└─┬ node-eventstore-client@0.2.0
  ├── long@3.2.0
  └─┬ protobufjs@6.7.3
    └── long@3.2.0
```

**Comment by nicdex** [comment]
Yes it's a bug in the client. There's a 64MB limit applied when receiving packets from the server, but not when sending to the server. This is why it only crashes when reading the information back.
I will do more testing around this and implement a fix.

**Comment by jvdlaar** [comment]
Sorry to bring up this old issue. But our projection is crashing on this error as well. Would this be caused by a single event that is above 64mb, or can it also be caused by all events in a batch combined to be above 64mb?

**Comment by nicdex** [comment]
Sorry for the late answer. It's both in the case of a batch all events combined have to be less than 64mb (actually a bit less, because of the other properties in the result message from the server)
Currently there is no way to change that 64mb limit, but you can reduce the size of your batch.

**Comment by jvdlaar** [comment]
Thank you for the information!
