### ISSUE TITLE
basic connection pattern

### ISSUE THREAD

**Issue by reharik** [nicdex/node-eventstore-client#52]
Hi, I'm trying to just get a basic connection singleton that will reconnect on close or disconnect. I was just wondering if you have a basic pattern that you use for this.  I've tried a couple different ones and they seem to intermittently close.  I know this is not your code that's wrong, but my implementation.
Here's what I have 
```
module.exports = function(nodeeventstoreclient, promiseretry, logger) {
  let connection;
  let connectionState = '';
  const getConnection = options => {
    if (connectionState === 'connected') {
      return connection;
    }

    if (!connection || connectionState === 'closed') {
      connection = nodeeventstoreclient.createConnection(
        {verbose: options.verbose, log: logger},
        {host: options.host, port: 1113});
    }

    connection.connect();

    connection.once('connected', tcpEndPoint => {
      connectionState = 'connected';
      console.log(`=========='connected'=========`);
      console.log('connected to eventstore');
      console.log(`==========END 'connected'=========`);
      logger.trace(`gesConnection: ${connection._connectionName}
 - ${JSON.stringify(tcpEndPoint, null, 4)}`);
    });

    connection.on('error', function(err) {
      connectionState = 'error';
      logger.error(`Error occurred on ES connection: ${connection._connectionName}`, err);
    });

    connection.on('closed', function(reason) {
      connectionState = 'closed';
      console.log(`==========CLOSED!!!!=========`);
      console.log('CLOSED!!!!');
      console.log(`==========END CLOSED!!!!=========`);

      logger.info(`ES connection: ${connection._connectionName} closed, reason:`, reason);
      connection = getConnection(options);
    });

    connection.on('disconnected', function(reason) {
      connectionState = 'closed';
      console.log(`=========="DISCONNECTED!!!"=========`);
      console.log('DISCONNECTED!!!');
      console.log(`==========END "DISCONNECTED!!!"=========`);

      logger.info(`ES connection: ${connection._connectionName} disconnected, reason:`, reason);
      connection = getConnection(options);
    });

    return connection;
  };
  return getConnection;
};
```

 then I have another module that exposes it and some functionality like so
```
module.exports = function(nodeeventstoreclient, eventstoreConnection, logger, events, uuid) {
  return function eventstore(options) {
    const configs = options.eventstore;
    const credentialsForAllEventsStream =
      new nodeeventstoreclient.UserCredentials(configs.systemUsers.admin, configs.systemUsers.adminPassword);

    const eventEmitterInstance = () => {
      const emitter = new events.EventEmitter();
      const emitEvent = (sub, e) => {
        emitter.emit('event', e);
      };
      return {
        emitter,
        emitEvent
      };
    };

    const liveProcessingStarted = () => {
      logger.trace('Caught up with previously stored events. Listening for new events.');
    };

    const subscriptionDropped = (subscription, reason, error) => {
      if (error) {
        logger.error(error);
      }
      logger.info('Subscription dropped.');
    };

    let connection = async () => {
      const conn = await eventstoreConnection(configs);
      if (conn._handler.state !== 'connected') {
        let msg = `Connection: ${conn._connectionName} is not connected!`;
        logger.error(msg);
        throw new Error(msg);
      }
      return conn;
    };

    const commandPoster = async function(command, commandName, continuationId) {
      // fortify commands with metadata like date and user
      let conn = await connection;
      command.createDate = new Date();
      let event = nodeeventstoreclient.createJsonEventData(
        uuid.v4(),
        command,
        {eventName: commandName, continuationId, streamType: 'command'},
        commandName);
      await conn.appendToStream(
        'command',
        nodeeventstoreclient.expectedVersion.any,
        [event],
        credentialsForAllEventsStream);
    };

    return {
      eventEmitterInstance,
      liveProcessingStarted,
      subscriptionDropped,
      gesConnection: connection,
      createEventData: nodeeventstoreclient.createEventData,
      createJsonEventData: nodeeventstoreclient.createJsonEventData,
      expectedVersion: nodeeventstoreclient.expectedVersion,
      credentials: credentialsForAllEventsStream,
      commandPoster
    };
  };
};
```

I used to expose the connection like this
```
let connection = eventstoreConnection(configs); 
```
that seems to work when accessed like this
```let something = await connection;
something.appendToSteam()
```
but the command poster logic is 50/50.

I'm just hoping you have a simpler better pattern that works for you.
Thanks,
R

**Comment by nicdex** [comment]
I'm not sure that you need all that logic. The connection singleton returned by client.createConnection already has reconnection logic. Once 'connected' connection is guaranteed to handle reconnection on disconnects. If it can't reconnect after the configurable number of retries you'll get the 'error' and 'closed' event. At the point it means physical connection to the eventstore is lost or that the eventstore itself is down, so I'm not sure if it's worth continuing retrying to connect in those cases.

I usually setup my connection like this:

let connection = client.createConnection({}, 'tcp://localhost:1113');
connection.on('connected', () => console.log('Connection is ready to use for good.'));
connection.on('closed', () => {
   //Handle eventstore being un-accessible or down here
   //I usually have my app shutdown gracefully with an exit error and let external process manager handle failures (restarts + warning after X failures)
})

**Comment by reharik** [comment]
Oh, that is great to know, thank you.

As per your code example, do you then pass around the connection to modules that need it? Would you do that in a module then return { connection: connection }, require it in other modules and that creates the singleton? or is it that once you do that logic you can require('node-eventstore-client') and it returns the singleton?

Also, I'm not sure why my connection isn't working.  so I have 3 processes connecting to the eventstore using the same module that I shared part of.  Each in it's own container. The first two are subscribing to streams, the third is posting.  I find that intermittently the third one that posts, on first attempt to post, is disconnected.  I then touch a file in that process ( I'm using nodemon ) and it works. 
Seems strange

**Comment by reharik** [comment]
I'm not sure if you are using promises but does this look like it makes sense? 
(ignore the first function that's just dependency injection pretend it's not there and I required those two dependencies)
```
module.exports = function(nodeeventstoreclient, logger) {
  let connection;
  let connectionState = '';

  const getConnection = options => {

    let connection = nodeeventstoreclient.createConnection(
      {verbose: options.verbose, log: logger},
      {host: options.host, port: 1113});

    connection.on('closed', (reason) => {
      logger.info(`ES connection: ${connection._connectionName} closed, reason:`, reason);
      throw new Error(reason)
    });

    return connection.connect()
      .then(() => new Promise(res => {
        return connection.once('connected', tcpEndPoint => {
          connectionState = 'connected';
          console.log(`=========='connected'=========`);
          console.log('connected to eventstore');
          console.log(`==========END 'connected'=========`);
          logger.trace(`gesConnection: ${connection._connectionName}
 - ${JSON.stringify(tcpEndPoint, null, 4)}`);
          return res(connection);
        });
      }))
      .catch(err =>
        logger.error(`Error occurred on ES connection: ${connection._connectionName}`, err)
      );
   };

    return {
      getConnection
    };
  };

```

**Comment by nicdex** [comment]
Sorry about the delay. I think you have to register "connected" before calling connect(). I would also use two different handler for "error", before and after connected. connect() will only throw endpoint discovery errors, any connection i/o errors will be thrown via emit "error".

The code I'm using is:

`async function connectTo(connection, name, logger) {
    logger.info(`Connecting to ${name} GES...`);
    const connectionPromise = new Promise((resolve, reject) => {
        connection.once('closed', reject);
        connection.once('connected', endPoint => {
            connection.removeListener('error', reject);
            logger.info("Connected to", name, "GES at", endPoint);
            resolve();
        });
    });
    await connection.connect();
    return connectionPromise;
}`

then

`var esClient = require('node-eventstore-client');
var logger = console;
var conn = esClient.createConnection({}, "tcp://localhost:1113");
await connectTo(conn, "", logger);
conn.on('closed', () => {
  logger.info("Connection to GES lost. Terminating this process.");
  process.exit(-1);
})`

**Comment by reharik** [comment]
Great.  Good stuff.  Thank you, for clarification, are you saying that I should use two different on('closed') events or two different on('error') events?
Thanks,
Raif

**Comment by reharik** [comment]
This is what I have is someone is reading this and want's an alternative ( or if nicdex sees something wrong )

```
{
    gesConnection: async options => {
      // this is a backOff routine ( promise-retry ) that tries to hit the server via http
      await pingES(options);

      let gesConnection = nodeeventstoreclient.createConnection(
        {verbose: options.verbose, log: logger},
        {host: options.host, port: 1113});

      await gesConnection.connect();
      return new Promise((res, rej) => {
        gesConnection.once('closed', rej);
        gesConnection.once('connected', () => {
          gesConnection.removeListener('closed', rej);
          console.log(`=========='connected'=========`);
          console.log('connected to eventstore');
          console.log(`==========END 'connected'=========`);
          gesConnection.on('closed', reason => {
            logger.info(`ES gesConnection: ${gesConnection._connectionName} closed, reason:`, reason);
            logger.info("Connection to GES lost. Terminating this process.");
            process.exit(-1);
          });
          return res(gesConnection);
        });
      })
        .catch(err =>
          logger.error(`Error occurred on ES _connectionName: ${gesConnection._connectionName}`, err)
        );
    }
  };
```
then instantiate this on start up wrap the resulting promise in module ( I actually have some helper functions and I wrap them all together ) 
```
const gesConnection(myOptions);
```
then in consumer I 
```
const myConnection = await myGesModule.getConnection; // not a function, it's a property which is a promise on myGesModule;
```

Thanks for the help nicdex!

**Comment by nicdex** [comment]
Sorry about the delay. It looks good, except that closed doesn't return an exception, but I think there no issue with rejecting or throwing a string instead of an error, apart the missing callstack.
