### ISSUE TITLE
UserCredentials function on Client does nothing

### ISSUE THREAD

**Issue by cdimitroulas** [nicdex/node-eventstore-client#56]
Passing user credentials to the `Client` using the `UserCredentials` function [(see here)](https://github.com/nicdex/node-eventstore-client/blob/master/src/systemData/userCredentials.js) does not seem to have any effect.

I would have expected this to pass some default credentials for all future calls like `appendToStream` but it seems that is not the case.

1. If I have misunderstood, could you please explain what is the purpose of this function?
2. Can we come up with an implementation which makes sense for this to work as it can be cumbersome to have to pass credentials on each individual call

**Comment by nicdex** [comment]
The UserCredentials "function" is a class constructor. http://dev.nicdex.com/node-eventstore-client/docs/0.2.0/UserCredentials.html

To set default user credentials you have to pass options to the creationConnection function.

**Comment by nicdex** [comment]
Example

var defaultUserCrendentials = new client.UserCrendetials("admin","changeit");
var conn = client.createConnection({defaultUserCredentials}, 'tcp://localhost:1113');

**Comment by cdimitroulas** [comment]
Thanks for your help, I will try this out.

In the meantime, maybe it would be an idea to improve the docs for the `createConnection` function so that it's clearer what the settings object can contain? I will work on a PR for this but I think you will need to fill in some descriptions about what the different settings do as I will have no clue :sweat_smile:

**Comment by cdimitroulas** [comment]
PR is here https://github.com/nicdex/node-eventstore-client/pull/58

**Comment by nicdex** [comment]
PR is merged and deployed as 0.2.4
Closing this issue
