### ISSUE TITLE
PersistentSubscriptionNakEventAction is not exported

### ISSUE THREAD

**Issue by quorak** [nicdex/node-eventstore-client#63]
```
const {
  PersistentSubscriptionNakEventAction,
  PersistentSubscriptionSettings
} = require('node-eventstore-client')
```
PersistentSubscriptionSettings is defined while PersistentSubscriptionNakEventAction is `undefined`

It looks like the class is not exported. Would be great to have this enum to work with.

**Comment by nicdex** [comment]
Fixed in 0.2.8
