### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by Karabur** [nicdex/node-eventstore-client#70]
When making more than 10 catch-up subscriptions, I getting that warning. 
problem is in `EventStoreCatchUpSubscription._runSubscription`, every subscription adds a handler on connection's `connected` event. 

Either it should be multiplexed in connection (so in reality only one connection handler will be bound), or `setMaxListeners()` used to set higher limit on connection object.

This could be solved by manually calling `setMaxListeners()` but I would consider that as a workaround, as it is not directly obvious and require some debugging to figure out reason and solution. Would be better to have that limit raised internally or solved in other way.

**Comment by nicdex** [comment]
I prefer to leave the warning there, because it's a good "wrong usage" indicator.
I am curious and I also want to help so I'm asking...
Why are you running that many subscriptions in a single node process?

**Comment by Karabur** [comment]
Every projection in app read side has it's own subscriptions (currently we build mostly aggregate - specific projections, so each projection listen to $ce-* ES projection. Also sagas listen to specific ES projections to start on required events. So in very basic example, if I have more than 10 projections for which I want to build read side projections, I will get that error. Feels like pretty low number for me. 

EventStore have quite flexible projections system which allows to create endless streams with specific logic, and apparently each of those streams will have it's own listener. That is perfectly fine on ES side and perfectly fine on app side, but node-eventstore-client does limit the number for some reason not obvious for me.

If you can describe why having any more than several subscriptions is "wrong usage" and how that should be done in right way, would be great.

**Comment by nicdex** [comment]
It's not necessarily wrong, but I have two concerns

1) optimization, if you have 10 subscriptions then the client will transfer/process the same event 10 times.
2) doing multiple subscriptions is basically equivalent to having micro-services inside a single process, which in itself is not bad. the question is what is you expectation around consistency? are you expecting all projections to be consistent (at the same event at the same time) if so how do you guarantee this when you have multiple subscribers? a projection could run slower than the others

that's why I usually prefer one subscription to $all and dispatch the event myself so all my projections are sync. 
going eventually consistent is a whole other game and if you do so do micro-services and don't run everything in the same process it's just confusing.

**Comment by Karabur** [comment]
Well, my case is different from what you said, let me clarify:

1. every projection listen for different events. Lets say I have a User and Post aggregates. One projection will listen for $ce-user stream, processing all events for all users, another projection will listen for $ce-post stream, processing all events for all posts. So I already have 2 subscriptions, and each event processed once. I would easily have more than 10 subscriptions like that and it will be more effective than listen to $all and route or discard events in one single listener.

2. I have no problems with consistency - architecture built in a way to take that into account. But I do really have concerns about subscribing to $all.
 Every projection consistent at any moment of time, but two different projections can be inconsistent to each other at any singe moment. Completely fine.
  In the case consistency will be really important, I can make ES projection and have in special stream, taking example from above, if I need to Users and Posts projection to be consistent and in sync, I can make $user-post stream (using ES built-in projections) so every user and post event will came in order, and process them in consistent way. Again way better than listening to $all stream (remember there could be thousands of completely irrelevant events in $all). 

As a wrap up - I dont think what forcing every one of my microservices to process all events is a good architecture decision. Also I doubt what making one microservice for each stream is a good one either. 
In one microservice I want to process this set of events, in another - that.
 Perhaps it will be just one stream for high-frequency events in one microservice, or it could be 50 subscriptions for events which happen once in a while in another. Or it will make sence to group projections based on domain concerns. 

EventStore provides extreme level of flexibility to build well-balanced system, and would be great if node-eventstore-client will keep up with that level.

**Comment by nicdex** [comment]
No need to insult my work. You can always use another client if you're not happy with the level this one provides.

**Comment by Karabur** [comment]
Sorry if it sounded rude, I had no intention to blame your library or work in any way. I tried to explain my points as detailed as possible and believe they are legit and could make library better and more useful to everyone, but as an author you can do whatever you want of course.
