### ISSUE TITLE
Creating continuous projection does not send correct parameters compared to EventStore UI

### ISSUE THREAD

**Issue by Poimen** [nicdex/node-eventstore-client#74]
We are using the projection manager (via TypeScript) and it doesn't seem to be sending the correct values through to the API when creating a continuous projection.

The client is sending
```
POST on http://localhost:2113/projections/continuous?name=DebiCheck_CurrentDebiCheckMandates&type=JS&emit=1&trackEmittedStreams=true
```
This creates the projection fine but the `trackEmittedStreams=true` is not translated (i.e. the projection is created with this off).

If I track what the Event Store UI is sending, the options should be:
```
POST on http://localhost:2113/projections/continuous?name=test&emit=yes&checkpoints=yes&enabled=yes&trackemittedstreams=yes
```

Even if I hack TypeScripts definition to allow `trackEmittedStreams=yes` the projection is not created correctly.

This is using the v5 Event Store server, so not sure if this has changed. Event Store docs mention `true/false` as options but doesn't appear to be obeying it directly.

Before I continue to hack around, Is this a bug with their server or client?

There does seem to be options missing, not sure if this is intentional?

**Comment by nicdex** [comment]
It's a client issue. This parameter should be lowercase. Will fix.
