### ISSUE TITLE
Acknowledgements for Persistent Subscription

### ISSUE THREAD

**Issue by yantsishko** [nicdex/node-eventstore-client#87]
Hi, how can i acknowledgement event for persistent subscription using this client?

i sent event to subscription.

![image](https://user-images.githubusercontent.com/50244590/64422566-0bf47300-d0ad-11e9-93dc-c0a693fc5c97.png)

Each time, when i connect to subscription i get this Event.
In doc written, that last param in connectToPersistentSubscription is auto-ack (by default its true) and when handler for event return Promise resolve it should accept event and don't send it again.

i have code example
```

const esClient = require('node-eventstore-client');

let esConnection = null;

const start = async () => {
  console.log('start');
  const connSettings = {};  // Use defaults
  esConnection = esClient.createConnection(connSettings, "tcp://eventstore:1113");
  await esConnection.connect();

  const connectedPromise = new Promise((resolve, reject) => {
    esConnection.once('connected', resolve);
    const timeoutMs = 5000;
    const errorMsg =
      'Event Store connection failed after 5000ms timeout';
    const error = Error(errorMsg);
    setTimeout(() => reject(error), timeoutMs);
  });
  const tcpEndpoint = await connectedPromise;
  console.log('Connected to eventstore');

  await connectToSubscription();
};

const subscriptionDropped = () => {
  console.log('dropped');
};

const connectToSubscription = async () => {
  const credentials = new esClient.UserCredentials('admin', 'changeit');
  try {
    console.log('connectToSubscription start');
    const subscription = await esConnection.connectToPersistentSubscription(
      'TEST',
      'test',
      (subscription, event) => {
        console.log(JSON.parse(event.originalEvent.data.toString()));
        return Promise.resolve();
        },
      subscriptionDropped,
      credentials,
    );
    console.log('connectToSubscription end');
    return subscription;
  } catch (e) {
    console.log(e);
  }
};

start();
```

what i do incorrect? I tried to use acknowledge method manually, but no results..

**Comment by nicdex** [comment]
It works as expected. 
Events are auto-acknowledged, you can see it in the UI it says 0 in flight meaning they have been acked by the client.
When I run the code you provided more than once, in the subsequent runs I don't receive events received (and acked) from previous runs.

**Comment by yantsishko** [comment]
After some magic it works, thanks
