### ISSUE TITLE
Investigate Long that aren't in deserialized protobuf messages

### ISSUE THREAD

**Issue by nicdex** [nicdex/node-eventstore-client#91]
There's two PRs (#88 #89) submitted about this, but they fix the symptoms instead or fixing the issue.
Something must have changed in a recent version of protobuf that causes this issue.

**Comment by 0xb4lamx** [comment]
> Something must have changed in a recent version of protobuf that causes this issue.

nothing changed in `protobuf`.
the bug appears when a 3rd party package modifies the behavior of `protobufjs` by removing its support for Long.
example: [apollo-server](https://github.com/apollographql/apollo-server/blob/e8faacbd6150999abd5376de64d2a7e44e541f9d/packages/apollo-engine-reporting-protobuf/src/index.js#L2-L8).
#89 was a way to make sure that we treat all values as `Long` type.
you can make it better by treating `Long` & `number` separately.

**Comment by nicdex** [comment]
Fixed in 0.2.14
Pleased try it and let me know if everything works fine.
