### ISSUE TITLE
The status of this module is unclear

### ISSUE THREAD

**Issue by leopoldodonnell** [nicdex/node-eventstore-client#97]
Given that EventStore support for Nodejs is almost non-existent; this module appears to be only source for integration for Nodejs applications. Note that while it is not a top ten contender module, it does receive active interest.

Is this module being maintained?
Status should be indicated in the Readme as guidance.

Thx

**Comment by nicdex** [comment]
Well EventStore has an HTTP API that can be use from any language. This is a port of their TCP client for nodejs. The project is active, as in people are using it, issues are being fixed and closed. The standard is to add a notification if the project is unmaintained or deprecated, which it is not.
